# Generated by Django 2.2.5 on 2019-09-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('rated', models.CharField(max_length=10)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=300)),
                ('writer', models.CharField(max_length=300)),
                ('actors', models.CharField(max_length=300)),
                ('plot', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('awards', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=300)),
                ('imdb_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('box_office', models.CharField(max_length=50)),
                ('production', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=10)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviecommentsapi.Movie')),
            ],
        ),
    ]
