# Generated by Django 2.2.5 on 2019-09-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviecommentsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
