# Generated by Django 2.2.5 on 2019-09-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecommentsapi', '0002_auto_20190904_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dvd',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
