# Generated by Django 2.2.5 on 2019-09-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecommentsapi', '0004_auto_20190904_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_votes',
            field=models.CharField(max_length=50),
        ),
    ]
