# Generated by Django 2.2.5 on 2019-09-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviecommentsapi', '0005_auto_20190905_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='moviecommentsapi.Movie'),
        ),
    ]
