# Generated by Django 2.2.5 on 2019-09-05 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviecommentsapi', '0006_auto_20190905_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moviecommentsapi.Movie'),
        ),
    ]
