# Generated by Django 2.2.5 on 2019-09-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviecommentsapi', '0007_auto_20190905_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
