# Generated by Django 2.2.5 on 2019-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecommentsapi', '0009_auto_20190907_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.CharField(max_length=10),
        ),
    ]
