# Generated by Django 2.2.5 on 2019-09-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecommentsapi', '0011_auto_20190908_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.CharField(max_length=30),
        ),
    ]
